name: Ruff

on:
  push:
    paths:
      - ".github/workflows/ruff.yml"
      - "pyproject.toml"
      - "slicer_profiles_db/**/*.py"
      - "tests/**/*.py"
      - "tools/**/*.py"
  pull_request:
    paths:
      - ".github/workflows/ruff.yml"
      - "pyproject.toml"
      - "slicer_profiles_db/**/*.py"
      - "tests/**/*.py"
      - "tools/**/*.py"
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.16.0"
          args: "format --check ."
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.16.0"
          args: "check ."
